logstash:
  image: logstash:6.5.1
  volumes:
    - ./logstash.conf:/etc/logstash.conf
  environment:
    LOGSPOUT: ignore
  ports:
    - "5000:5000/tcp"
    - "5000:5000/udp"
  links:
    - elasticsearch 
  command: -f /etc/logstash.conf
elasticsearch: 
  image: elasticsearch:6.5.1
  environment:
    - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
kibana: 
  image: kibana:6.5.1
  environment:
    LOGSPOUT: ignore
    ELASTICSEARCH_URL: http://elasticsearch:9200
  links:
    - elasticsearch
  ports:
    - "5601:5601"
